### ISSUE TITLE
[setup info] - what´s wrong that vscode did not recognised method calls

### ISSUE THREAD

**Issue by rbartholomay** [reg2005/adonis5-scheduler#1]
Hi!

i installed it an all runs fine... But VSCode and the Typescript compiler throws some errors...  Why?

![image](https://user-images.githubusercontent.com/1138142/88137808-a5a51000-cbec-11ea-948b-932d2a57cbad.png)

![image](https://user-images.githubusercontent.com/1138142/88137839-b6ee1c80-cbec-11ea-9970-fdc0d66f5cb3.png)

Any idea?

**Comment by reg2005** [comment]
Just use global ioc logger instance like:
```ts
import Logger from '@ioc:Adonis/Core/Logger'

```
