### ISSUE TITLE
TypeError: this.container.singleton is not a function

### ISSUE THREAD

**Issue by mauriciopfl** [reg2005/adonis5-scheduler#11]
![image](https://user-images.githubusercontent.com/12702629/117970300-e34f6280-b2fe-11eb-9e39-904e291e0055.png)

**Comment by carlos-barbier** [comment]
Getting the same error

**Comment by ucheubani96** [comment]
Also getting the same error. Anyone know what's the cause?

**Comment by reg2005** [comment]
Hello! I fixed it, please upgrade to 2.0.2
