### ISSUE TITLE
No types

### ISSUE THREAD

**Issue by hadnet** [reg2005/adonis5-scheduler#18]
## Description
When using 
```ts
import {BaseTask} from 'adonis5-scheduler/build';
```
IDE says could not find a declaration file for module 'adonis5-scheduler/build'

## Package version
2.0.2

## Error Message & Stack Trace

Could not find a declaration file for module 'adonis5-scheduler/build'. '.../node_modules/adonis5-scheduler/build/index.js' implicitly has an 'any' type.

## Relevant Information

Adonis 5.1.8

**Comment by davidlandais** [comment]
Have you found a workaround ?

**Comment by antoniosilva000000** [comment]
Any solution?

**Comment by Nawaytes** [comment]
me too have this problem

**Comment by palfaro91** [comment]
Has anyone found a solution?

**Comment by reg2005** [comment]
Just use 
import { BaseTask } from 'adonis5-scheduler/build/src/Scheduler/Task'

instead of
import {BaseTask} from 'adonis5-scheduler/build';

The template for node ace make:task has been fixed, you can update the package
