### ISSUE TITLE
Name of task class cannot be in CamelCase format when using lock

### ISSUE THREAD

**Issue by ErnaniR** [reg2005/adonis5-scheduler#19]
## Description

I'm getting a strange bug. If I create a task and enable the lock, but the class name is in camel case, an error is thrown. It seems there is an erroneous conversion of class name into lock file name.
For example, here is the same task from the explanation video in the docs, but the name is `TaskToCheckSomething` instead of `Test`:

```typescript
import Logger from '@ioc:Adonis/Core/Logger'
import { BaseTask } from 'adonis5-scheduler/build'

export default class TaskToCheckSomething extends BaseTask {
  public static get schedule() {
    return '*/1 * * * * *'
  }

  public static get useLock() {
    return true
  }

  public async handle() {
    const ms = new Date().getTime()
    Logger.info('handle start', ms)
    await new Promise((resolve) => setTimeout(resolve, 3000))
    Logger.info('handle end', ms)
  }
}
```
This will throw an invalid argument error, as it is trying to create a lock file with the name `\tmpLock\task:to:check:something.lock'`.
If I change the class name to Tasktochecksomething the error does not occur.

## Package version
2.0.2

## Error Message & Stack Trace
Start the program with `node ace serve --watch` in the console and:

```
[1628704860016] FATAL (project-name/19356 on DESKTOP-XXXXX): "uncaughtException" detected. Process will shutdown
Error: EINVAL: invalid argument, mkdir 'C:\Path\to\project\project-name\tmpLock\task:to:check:something.lock'
[ warn ]  Underlying HTTP server died with "1 code"
```

## Relevant Information
Adonis 5.1.0

**Comment by reg2005** [comment]
[Fixed](https://github.com/reg2005/adonis5-scheduler/commit/a5ee7595ba00c89dd7218903a75b65a3ae763e48#diff-4226b8ccb952a56df609164e2726a7b0ca9e05277e369dc09c29ba4da0793d0f), please upgrade package
