### ISSUE TITLE
[feature request] Friendly API

### ISSUE THREAD

**Issue by AGDholo** [reg2005/adonis5-scheduler#2]
## Description

Ref: https://laravel.com/docs/8.x/scheduling#schedule-frequency-options

In the execution of some common time points, people no need to learn the syntax of cron.

**Comment by reg2005** [comment]
[Ok](https://github.com/reg2005/adonis5-scheduler/blob/53166b9f4b474c533944b4df02b170d417397f1b/templates/taskTemplate.txt#L6), please update package
