### ISSUE TITLE
Is there any way to set a timezone?

### ISSUE THREAD

**Issue by antoniosilva000000** [reg2005/adonis5-scheduler#26]
**Is there any way to set a timezone?**

Hi, I'm from Argentina and I'm going to host my app outside of my timezone, is there any option to set a specific timezone?

My scheduler is set to run every day at 11pm:
0 23 * * *

So depending on where I host my app, my task might run at an unexpected time.

**Comment by Nawaytes** [comment]
you can try running the scheduler every minute,

then compare the time with the one you want. for example, if it's 11pm. you can run the function

**Comment by neliocaa** [comment]
> **Is there any way to set a timezone?**
> 
> Hi, I'm from Argentina and I'm going to host my app outside of my timezone, is there any option to set a specific timezone?
> 
> My scheduler is set to run every day at 11pm: 0 23 * * *
> 
> So depending on where I host my app, my task might run at an unexpected time.

You can add TZ='America/Argentina/Buenos_Aires' on your .env
