### ISSUE TITLE
How to make cron auto start

### ISSUE THREAD

**Issue by soonzhi** [reg2005/adonis5-scheduler#3]
How to make this cron auto start when start the server.js

**Comment by reg2005** [comment]
Make file: start/scheduler.ts with content:
```ts
const scheduler = Application.container.use('Adonis/Addons/Scheduler')
scheduler.run()
```
And register it in [preloads](https://docs.adonisjs.com/guides/adonisrc-file#preloads)

**Comment by henriquechagasg** [comment]
> Make file: start/scheduler.ts with content:
> 
> ```ts
> const scheduler = Application.container.use('Adonis/Addons/Scheduler')
> scheduler.run()
> ```
> 
> And register it in [preloads](https://docs.adonisjs.com/guides/adonisrc-file#preloads)

Hi @reg2005 , unfortnately, I'm having the error: "Property 'container' does not exist on type 'typeof Application".
Is there any other way that o could do that ?

**Comment by henriquechagasg** [comment]
> > Make file: start/scheduler.ts with content:
> > ```ts
> > const scheduler = Application.container.use('Adonis/Addons/Scheduler')
> > scheduler.run()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And register it in [preloads](https://docs.adonisjs.com/guides/adonisrc-file#preloads)
> 
> Hi @reg2005 , unfortnately, I'm having the error: "Property 'container' does not exist on type 'typeof Application". Is there any other way that o could do that ?

Just found the answer. If anyone needs, checkout: https://github.com/adonisjs/core/discussions/2033#discussioncomment-208350

**Comment by pixelpaulaus** [comment]
i dont see anywhere in the docs on how to start in via a preload file.
