### ISSUE TITLE
Bug : Cant create lock file on windows

### ISSUE THREAD

**Issue by ouraios** [reg2005/adonis5-scheduler#31]
Adonis5-scheduler is tryign to create a lock file with colon in its name but on windows colon is not accepted in naming a folder or a file.

Line of code incriminated : https://github.com/reg2005/adonis5-scheduler/blob/2a9960bc3c294a9d73049dd8ae080841e65f6aea/src/Scheduler/Task.ts#L40

This line of code need to replace the colon with for example an hyphen and this will work in both linux and windows OS :+1:

**Comment by reg2005** [comment]
[Fixed](https://github.com/reg2005/adonis5-scheduler/commit/a5ee7595ba00c89dd7218903a75b65a3ae763e48#diff-4226b8ccb952a56df609164e2726a7b0ca9e05277e369dc09c29ba4da0793d0f), please upgrade package
