### ISSUE TITLE
After I close my ubuntu server terminal the scheduler stops performing . It is only running when I give the command node ace scheduler: run and keep the terminal open . how to keep it always running even without the terminal ?

### ISSUE THREAD

**Issue by imtiiiii** [reg2005/adonis5-scheduler#34]
## Prerequisites

We do our best to reply to all the issues on time. If you will follow the given guidelines, the turn around time will be faster.

- Ensure the issue isn't already reported.
- Ensure you are reporting the bug in the correct repo.

*Delete the above section and the instructions in the sections below before submitting*

## Description

If this is a feature request, explain why it should be added. Specific use-cases are best.

For bug reports, please provide as much *relevant* info as possible.

**Comment by cloleb** [comment]
Check: https://github.com/adonisjs/core/discussions/2033#discussioncomment-208350
