### ISSUE TITLE
Is there any specific usecase for multiple servers with Load balancers

### ISSUE THREAD

**Issue by roqkabel** [reg2005/adonis5-scheduler#37]
## Description

I am using Adonis 5 on Kubernetes with a Load Balancer.
I am planning of executing some tasks using the Scheduler ( Adonis5-scheduler)

I am wondering how it is going to work in my use case.

Please share if you have any idea of how I can go about this 

Thanks in Advance.

**Comment by reg2005** [comment]
You need run single instance with command "node ace scheduler:run".  And run multiple instances your app "node ace serve"
