### ISSUE TITLE
Task is not running or i can't watch the running.

### ISSUE THREAD

**Issue by waldandrade** [reg2005/adonis5-scheduler#4]
## Prerequisites

I'm using Adonis 5 following the instructions to setup the lib.
I'm creating a Task.

"adonis5-scheduler": "^1.0.1

## Description

When run 'node ace scheduler:run', a received a success message but i'ts not running.

![image](https://user-images.githubusercontent.com/11839129/99803060-87f2a380-2b17-11eb-92c7-6c43e581c967.png)

**Comment by reg2005** [comment]
Hello! Please upgrade to 2.0.2
