### ISSUE TITLE
Method SchedulerRun.handle is Deprecated

### ISSUE THREAD

**Issue by mvofreire** [reg2005/adonis5-scheduler#7]
![image](https://user-images.githubusercontent.com/4127341/110227060-1cb8bb80-7ed3-11eb-8dfd-f1b0e52d1d23.png)

**Comment by arthurcvm** [comment]
Hi @mvofreire, you solve this?

**Comment by mvofreire** [comment]
Not yet... It seems to be something related to the interface exported in the register.
![image](https://user-images.githubusercontent.com/4127341/115019549-b9398a80-9e8f-11eb-803e-05bb13038d38.png)

**Comment by gferr-menezes** [comment]
same problem here

**Comment by rafaelncarvalho** [comment]
https://github.com/adonisjs/core/discussions/2033#discussioncomment-208350

I added to run automatic and it's working now

**Comment by arthurcvm** [comment]
Hi!
I solve the problem with this structure:
[https://github.com/arthurcvm/cronjob-adonisjs5](https://github.com/arthurcvm/cronjob-adonisjs5)

**Comment by reg2005** [comment]
Hello! Please upgrade to 2.0.2
