### ISSUE TITLE
This project is dead?

### ISSUE THREAD

**Issue by arthurcvm** [reg2005/adonis5-scheduler#8]
@reg2005 please, reply the issues and build a complete instructions to configure and use.
We need a complete documentation to use.

**Comment by filipe-mariz** [comment]
I totally agree! I've been trying to make a Schedule for 1 week and the documentation doesn't help me and nothing

**Comment by arthurcvm** [comment]
Hi @filipe-mariz, I solve with [this structure](https://github.com/arthurcvm/cronjob-adonisjs5)

**Comment by reg2005** [comment]
Hello! Sorry for waiting. Please upgrade to 2.0.2
